# Kafka
spring:
  kafka:
    streams:
      application-id: spring-boot-streams
      replication-factor: 3
    properties:
      security:
        protocol: SASL_SSL
      bootstrap:
        servers: ${SERVER}
      sasl:
        mechanism: PLAIN
        jaas:
          config: ${CREDENTIALS}
    producer:
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: group_id
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.LongDeserializer
